### ISSUE TITLE
File does not exist, please check your file path

### ISSUE THREAD

**Issue by kuangzhuoran** [wangjk321/H1D_documents#2]
Hi !
When I run "h1d call stripeTAD"   (h1d version 0.1.29; CentOS Stream release 8;)
I met this error:

"
Start dump matrix from hic file
Finish dump
File does not exist, please check your file path
"

It seems to be because the input file is not found, but the path to the input file is actually correct, 
and I've tried the absolute path as well。

my command is "h1d call stripeTAD ./carmeli.30.hic 25000 Chr29 -o carmeli.Chr29.dTAD --datatype rawhic --gt ./carmeli.length"

This file does exist：
![This file does exist.](https://github.com/wangjk321/H1D_documents/assets/76553133/77d9df64-3c72-4096-9bd8-4b768d436201)

**Comment by kuangzhuoran** [comment]
Sorry, I think I know why.

**Comment by kuangzhuoran** [comment]
I'm sorry to say that the rest of the analyses are experiencing this problem.

**Comment by wangjk321** [comment]
Can you describe your question more, I cannot catch what your problem is. And please open a issue here https://github.com/wangjk321/HiC1Dmetrics/issues .
